/**
 * Theme Registry - Auto-generated from theme files
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run 'npm run generate-theme-types' to regenerate
 */

export type ThemeId =
  | 'kpop-rainbow'
  | 'terminal-dark'
  | 'custom'

export type ThemeCategory = 'light' | 'dark'

export interface ThemeMetadata {
  id: ThemeId
  name: string
  description: string
  category: ThemeCategory
  author: string
  version: string
  preview: {
    primary: string
    background: string
    accent: string
  }
}

// Theme registry
export const themes: Record<Exclude<ThemeId, 'custom'>, ThemeMetadata> = {
  'kpop-rainbow': {
    "id": "kpop-rainbow",
    "name": "K-pop Rainbow Unicorn",
    "description": "Playful and vibrant theme with rainbow colors and soft pastels",
    "category": "light",
    "author": "DesignVibe",
    "version": "1.0.0",
    "preview": {
      "primary": "#FF1F8E",
      "background": "#FFF5FB",
      "accent": "#FF6B9D"
    }
  },
  'terminal-dark': {
    "id": "terminal-dark",
    "name": "Terminal Dark",
    "description": "Cyberpunk terminal aesthetic with neon green accents",
    "category": "dark",
    "author": "DesignVibe",
    "version": "1.0.0",
    "preview": {
      "primary": "#00ff41",
      "background": "#0a0e14",
      "accent": "#00e5ff"
    }
  }
}

// Utility functions
export function getTheme(id: Exclude<ThemeId, 'custom'>): ThemeMetadata {
  return themes[id]
}

export function getThemesByCategory(category: ThemeCategory): ThemeMetadata[] {
  return Object.values(themes).filter(theme => theme.category === category)
}

export function getDefaultTheme(): ThemeId {
  return 'terminal-dark'
}

export function isValidThemeId(id: string): id is ThemeId {
  return id === 'custom' || id in themes
}

export function getAllThemes(): ThemeMetadata[] {
  return Object.values(themes)
}
