/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'var(--color-semantic-border)',
        input: 'var(--color-semantic-input-background)',
        ring: 'var(--color-semantic-border-focus)',
        background: 'var(--color-semantic-background)',
        foreground: 'var(--color-semantic-foreground)',
        primary: {
          DEFAULT: 'var(--color-semantic-primary)',
          foreground: 'var(--color-palette-surface-base)',
          hover: 'var(--color-semantic-primary-hover)',
        },
        secondary: {
          DEFAULT: 'var(--color-semantic-secondary)',
          foreground: 'var(--color-semantic-secondary-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--color-semantic-error)',
          foreground: 'var(--color-palette-surface-base)',
        },
        muted: {
          DEFAULT: 'var(--color-semantic-muted)',
          foreground: 'var(--color-semantic-foreground-muted)',
        },
        accent: {
          DEFAULT: 'var(--color-semantic-accent)',
          foreground: 'var(--color-palette-surface-base)',
        },
        popover: {
          DEFAULT: 'var(--color-semantic-background-elevated)',
          foreground: 'var(--color-semantic-foreground)',
        },
        card: {
          DEFAULT: 'var(--color-semantic-background-elevated)',
          foreground: 'var(--color-semantic-foreground)',
        },
        success: 'var(--color-semantic-success)',
        warning: 'var(--color-semantic-warning)',
        error: 'var(--color-semantic-error)',
        info: 'var(--color-semantic-info)',
      },
      fontFamily: {
        sans: 'var(--font-family-sans)'.split(',').map(f => f.trim().replace(/"/g, '')),
        mono: 'var(--font-family-mono)'.split(',').map(f => f.trim().replace(/"/g, '')),
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
      },
      fontWeight: {
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      lineHeight: {
        tight: 'var(--font-lineHeight-tight)',
        normal: 'var(--font-lineHeight-normal)',
        relaxed: 'var(--font-lineHeight-relaxed)',
      },
      spacing: {
        0: 'var(--spacing-0)',
        1: 'var(--spacing-1)',
        1.5: 'var(--spacing-1\\.5)',
        2: 'var(--spacing-2)',
        2.5: 'var(--spacing-2\\.5)',
        3: 'var(--spacing-3)',
        3.5: 'var(--spacing-3\\.5)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        7: 'var(--spacing-7)',
        8: 'var(--spacing-8)',
        10: 'var(--spacing-10)',
        12: 'var(--spacing-12)',
        16: 'var(--spacing-16)',
        20: 'var(--spacing-20)',
        24: 'var(--spacing-24)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-base)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-base)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        focus: 'var(--shadow-focus)',
        accent: 'var(--shadow-accent)',
      },
      transitionDuration: {
        fast: 'var(--transition-duration-fast)',
        DEFAULT: 'var(--transition-duration-base)',
        slow: 'var(--transition-duration-slow)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--transition-timing-ease)',
      },
      borderWidth: {
        0: 'var(--border-width-0)',
        DEFAULT: 'var(--border-width-1)',
        2: 'var(--border-width-2)',
        4: 'var(--border-width-4)',
      },
      opacity: {
        0: 'var(--opacity-0)',
        10: 'var(--opacity-10)',
        20: 'var(--opacity-20)',
        30: 'var(--opacity-30)',
        40: 'var(--opacity-40)',
        50: 'var(--opacity-50)',
        60: 'var(--opacity-60)',
        70: 'var(--opacity-70)',
        80: 'var(--opacity-80)',
        90: 'var(--opacity-90)',
        100: 'var(--opacity-100)',
      },
      zIndex: {
        0: 'var(--zIndex-base)',
        10: 'var(--zIndex-dropdown)',
        20: 'var(--zIndex-sticky)',
        30: 'var(--zIndex-fixed)',
        40: 'var(--zIndex-overlay)',
        50: 'var(--zIndex-modal)',
        60: 'var(--zIndex-popover)',
        70: 'var(--zIndex-tooltip)',
        100: 'var(--zIndex-toast)',
      },
      minWidth: {
        input: 'var(--size-input-min-width)',
      },
      minHeight: {
        textarea: 'var(--size-textarea-min-height)',
      },
      maxWidth: {
        dialog: 'var(--size-dialog-max-width)',
      },
      width: {
        'icon-xs': 'var(--size-icon-xs)',
        'icon-sm': 'var(--size-icon-sm)',
        'icon-md': 'var(--size-icon-md)',
        'icon-base': 'var(--size-icon-base)',
        'icon-lg': 'var(--size-icon-lg)',
        'icon-xl': 'var(--size-icon-xl)',
      },
      height: {
        'icon-xs': 'var(--size-icon-xs)',
        'icon-sm': 'var(--size-icon-sm)',
        'icon-md': 'var(--size-icon-md)',
        'icon-base': 'var(--size-icon-base)',
        'icon-lg': 'var(--size-icon-lg)',
        'icon-xl': 'var(--size-icon-xl)',
        input: 'var(--size-input-height)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        blink: {
          '0%, 50%': { opacity: '1' },
          '51%, 100%': { opacity: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        blink: 'blink 1s step-end infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
