/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'var(--color-semantic-border)',
        input: 'var(--color-semantic-input-background)',
        ring: 'var(--color-semantic-border-focus)',
        background: 'var(--color-semantic-background)',
        foreground: 'var(--color-semantic-foreground)',
        primary: {
          DEFAULT: 'var(--color-semantic-primary)',
          foreground: 'var(--color-terminal-black)',
          hover: 'var(--color-semantic-primary-hover)',
        },
        secondary: {
          DEFAULT: 'var(--color-terminal-gray-700)',
          foreground: 'var(--color-terminal-green)',
        },
        destructive: {
          DEFAULT: 'var(--color-semantic-error)',
          foreground: 'var(--color-terminal-black)',
        },
        muted: {
          DEFAULT: 'var(--color-terminal-gray-800)',
          foreground: 'var(--color-semantic-foreground-muted)',
        },
        accent: {
          DEFAULT: 'var(--color-terminal-cyan)',
          foreground: 'var(--color-terminal-black)',
        },
        popover: {
          DEFAULT: 'var(--color-semantic-background-elevated)',
          foreground: 'var(--color-semantic-foreground)',
        },
        card: {
          DEFAULT: 'var(--color-semantic-background-elevated)',
          foreground: 'var(--color-semantic-foreground)',
        },
        success: 'var(--color-semantic-success)',
        warning: 'var(--color-semantic-warning)',
        error: 'var(--color-semantic-error)',
        info: 'var(--color-semantic-info)',
        terminal: {
          black: 'var(--color-terminal-black)',
          'black-light': 'var(--color-terminal-black-light)',
          green: 'var(--color-terminal-green)',
          'green-dim': 'var(--color-terminal-green-dim)',
          amber: 'var(--color-terminal-amber)',
          cyan: 'var(--color-terminal-cyan)',
          red: 'var(--color-terminal-red)',
          blue: 'var(--color-terminal-blue)',
          purple: 'var(--color-terminal-purple)',
          gray: {
            50: 'var(--color-terminal-gray-50)',
            100: 'var(--color-terminal-gray-100)',
            200: 'var(--color-terminal-gray-200)',
            300: 'var(--color-terminal-gray-300)',
            400: 'var(--color-terminal-gray-400)',
            500: 'var(--color-terminal-gray-500)',
            600: 'var(--color-terminal-gray-600)',
            700: 'var(--color-terminal-gray-700)',
            800: 'var(--color-terminal-gray-800)',
            900: 'var(--color-terminal-gray-900)',
          },
        },
      },
      fontFamily: {
        sans: 'var(--font-family-sans)'.split(',').map(f => f.trim().replace(/"/g, '')),
        mono: 'var(--font-family-mono)'.split(',').map(f => f.trim().replace(/"/g, '')),
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
      },
      fontWeight: {
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      lineHeight: {
        tight: 'var(--font-lineHeight-tight)',
        normal: 'var(--font-lineHeight-normal)',
        relaxed: 'var(--font-lineHeight-relaxed)',
      },
      spacing: {
        0: 'var(--spacing-0)',
        1: 'var(--spacing-1)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        8: 'var(--spacing-8)',
        10: 'var(--spacing-10)',
        12: 'var(--spacing-12)',
        16: 'var(--spacing-16)',
        20: 'var(--spacing-20)',
        24: 'var(--spacing-24)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-base)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-base)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        'glow-green': 'var(--shadow-glow-green)',
        'glow-cyan': 'var(--shadow-glow-cyan)',
      },
      transitionDuration: {
        fast: 'var(--transition-duration-fast)',
        DEFAULT: 'var(--transition-duration-base)',
        slow: 'var(--transition-duration-slow)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--transition-timing-ease)',
      },
      borderWidth: {
        0: 'var(--border-width-0)',
        DEFAULT: 'var(--border-width-1)',
        2: 'var(--border-width-2)',
        4: 'var(--border-width-4)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        blink: {
          '0%, 50%': { opacity: '1' },
          '51%, 100%': { opacity: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        blink: 'blink 1s step-end infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
